### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by marthacryan**
Updates the package.json to make a new release for the ToC extension.

### CODE REVIEW

**Comment by lresende** [comment]
@kgryte just adding you for your awareness, I will wait and merge/release by tomorrow.

**Comment by kgryte** [comment]
@lresende Awesome! Thanks!

**Comment by kgryte** [comment]
I assume that this has been tested out locally?

**Comment by marthacryan** [comment]
@kgryte Yes, everything looks good.

**Comment by kgryte** [comment]
@marthacryan Awesome! Thank you for so much for verifying and working on this!

**Pull request merged**
