### PR TITLE
Revert "Auto numbering"

### PR DESCRIPTION
**Pull request by zuoyuanh**
Reverts jupyterlab/jupyterlab-toc#29

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Hi @zuoyuanh and @markellekelly, do you want me to remove these commits?

**Comment by zuoyuanh** [comment]
Yes please. I'm sorry I accidentally merged them.

**Comment by ian-r-rose** [comment]
No problem! I have "unmerged" these. Your branches should be unaffected.

**Comment by ian-r-rose** [comment]
Also, feel free to let me know if you want to talk through any of the features you are implementing.

**Pull request merged**
