### PR TITLE
Collapsing fixes

### PR DESCRIPTION
**Pull request by markellekelly**
Re-worked collapsing to fix some issues, specifically issue #53 and some parent/child problems when filtering by tags

### CODE REVIEW

**Comment by markellekelly** [comment]
@ian-r-rose would love to hear your feedback on this when you get a chance!

**Comment by ian-r-rose** [comment]
Sorry to be so slow @markellekelly! I'll review tomorrow.

**Comment by ian-r-rose** [comment]
@markellekelly, sorry to be so slow! I am seeing some headings that are getting collapsers when they shouldn't. My test notebook has been [this one](https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/03.11-Working-with-Time-Series.ipynb). For instance, the `Resampling and converting frequencies` heading has a collapser, when it should be a leaf header:
image

In general, I am finding the code for generating the collapsers to be kind of confusing, and it has a lot of under-documented state to it, which makes this tough for me to figure out...

**Comment by ian-r-rose** [comment]
Also, can I ask you to make the PR in a feature branch? It makes testing and reviews more challenging when we are comparing `master` to `master`.

**Comment by ian-r-rose** [comment]
Here is a simpler example of where a heading incorrectly gets a collapser:
image

**Comment by ian-r-rose** [comment]
As far as I can tell this is superseded by #70, let me know if that's wrong!

**Pull request closed without merging**
